const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
const COLLECTION_WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_WORKSPACES_ID!;
const COLLECTION_MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_MEMBERS_ID!;
const BUCKET_IMAGES_ID = process.env.NEXT_PUBLIC_APPWRITE_BUCKET_IMAGES_ID!;

export {DATABASE_ID, COLLECTION_WORKSPACES_ID, COLLECTION_MEMBERS_ID, BUCKET_IMAGES_ID};