const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DATABASE_ID!;
const COLLECTION_WORKSPACES_ID = process.env.NEXT_PUBLIC_APPWRITE_COLLECTION_WORKSPACES_ID!;

export {DATABASE_ID, COLLECTION_WORKSPACES_ID};